version: '3'
services:
  opensearch-node:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200  # OpenSearch node runs on port 9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.10.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601  # OpenSearch Dashboards interface
    environment:
      OPENSEARCH_USERNAME: 'admin'
      OPENSEARCH_PASSWORD: 'admin'
      OPENSEARCH_HOSTS: '["http://opensearch-node:9200"]'  # Connect to OpenSearch node on port 9200
      OPENSEARCH_SECURITY_ENABLED: 'true'  # Disable security
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
